// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC235BqFFMJHfGuyW4xDRikZ6SEpwv0Sg',
    appId: '1:916670046571:web:25e4e76485fdef1d09ec2e',
    messagingSenderId: '916670046571',
    projectId: 'todoer-104df',
    authDomain: 'todoer-104df.firebaseapp.com',
    storageBucket: 'todoer-104df.appspot.com',
    measurementId: 'G-R3FM7195PC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv_lyI1TfM8Bly8jUg6XLJRmbfJ6Hhd2M',
    appId: '1:916670046571:android:6169bb68a21a7d8f09ec2e',
    messagingSenderId: '916670046571',
    projectId: 'todoer-104df',
    storageBucket: 'todoer-104df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkYDADQXzZFbebyS_lVyrl8J5c5sHJ1KI',
    appId: '1:916670046571:ios:2418e51080d9e06709ec2e',
    messagingSenderId: '916670046571',
    projectId: 'todoer-104df',
    storageBucket: 'todoer-104df.appspot.com',
    iosClientId: '916670046571-dvjloeok12ehcpi3i9jrt19kl477gv7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkYDADQXzZFbebyS_lVyrl8J5c5sHJ1KI',
    appId: '1:916670046571:ios:2418e51080d9e06709ec2e',
    messagingSenderId: '916670046571',
    projectId: 'todoer-104df',
    storageBucket: 'todoer-104df.appspot.com',
    iosClientId: '916670046571-dvjloeok12ehcpi3i9jrt19kl477gv7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoer',
  );
}
